- name: Deploy notifier
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    aws_region: us-east-1

  tasks:

    - include: roles/include/tasks/lambda.yml
      vars:
        function_name: wichtel-notifier

    - include: roles/include/tasks/lambda.yml
      vars:
        function_name: wichtel-email
