---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  LambdaEmailFunctionName:
    Type: String
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
            Sid: ""
            Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: "WichtelEmailPermissions"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "ses:SendEmail"
                Resource: "*"
  EmailSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: wichtel-emails
      Subscription:
        - Endpoint:
            Fn::Join:
              - ""
              -
                - "arn:aws:lambda:"
                - Ref:
                    AWS::Region
                - ":"
                - Ref:
                    AWS::AccountId
                - ":function:"
                - Ref:
                    LambdaEmailFunctionName
          Protocol: lambda
Outputs:
  LambdaExecutionRole:
    Value:
      Fn::GetAtt:
        - "LambdaExecutionRole"
        - "Arn"
